-- 0015: Content Editorial Reviews (STEP 15B)
-- content_review: Immutable editorial review history for content variants generated by Critic.

CREATE TABLE content_review (
  id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL REFERENCES workspace (id) ON DELETE RESTRICT,
  content_id TEXT NOT NULL REFERENCES content (id) ON DELETE RESTRICT,
  content_variant_id TEXT NOT NULL REFERENCES content_variant (id) ON DELETE RESTRICT,
  critic_agent_id TEXT NOT NULL REFERENCES agent (id) ON DELETE RESTRICT,
  critic_agent_version_id TEXT NOT NULL REFERENCES agent_version (id) ON DELETE RESTRICT,
  ai_execution_id TEXT NOT NULL,
  verdict TEXT NOT NULL CHECK (verdict IN ('pass', 'revise')),
  review_json TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_content_review_variant ON content_review (content_variant_id, created_at DESC);
CREATE INDEX idx_content_review_content ON content_review (content_id, created_at DESC);
CREATE INDEX idx_content_review_workspace ON content_review (workspace_id, created_at DESC);
