/**
 * Cloudflare Worker bindings for this app.
 *
 * `Env` is generated by `npm run cf-typegen` (worker-configuration.d.ts,
 * gitignored) from wrangler.jsonc. This alias keeps application code
 * independent of the generated name. Regenerate after changing bindings.
 */
export type CloudflareBindings = Env
